name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["category: bug"]

body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!
        ### The following information will help us resolve your issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?

        If you can, please include a minimal code snippet that reproduces the issue.

        If you have a Traceback, please include the entire message.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - M1 macOS
        - Linux
  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      options:
        - earlier
        - 3.9
        - "3.10"
        - "3.11"
        - "3.12"
  - type: dropdown
    id: streaming
    attributes:
      label: Were you streaming with ROS3?
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: package_versions
    attributes:
      label: Package Versions
      description: |
        Please share your currently installed Python package versions by calling `pip list > environment_for_issue.txt` and uploading the text file along with this issue.

        This helps us determine if there are any secondary or tertiary issues caused by other dependencies.

        You can attach images or log files by clicking this area to highlight it and then dragging files in.
        If GitHub upload is not working, you can also copy and paste the output into this section.
      value: "<details> Copy and paste your output here </details>"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
          required: true
        - label: To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?
          required: true
