# Use this for mapping to external links
extlinks = {
    # "nwb_extension_git": ("https://github.com/nwb-extensions/%s", ""),
    # "ndx-catalog": ("https://nwb-extensions.github.io/", ""),
    # "pynwb-issue": ("https://github.com/NeurodataWithoutBorders/pynwb/issues/%s", "pynwb#%s"),
    # "pynwb-src": ("https://github.com/NeurodataWithoutBorders/pynwb/", ""),
    "pynwb-docs": ("https://pynwb.readthedocs.io/en/stable/", "%s"),
    # "hdmf-docs": ("https://hdmf.readthedocs.io/en/stable/", ""),
    # "hdmf-src": ("https://github.com/hdmf-dev/hdmf", ""),
    "matnwb-src": ("https://github.com/NeurodataWithoutBorders/matnwb", "%s"),
    # "matnwb-docs": ("https://neurodatawithoutborders.github.io/matnwb/", ""),
    # "nwbconversiontool-docs": ("https://nwb-conversion-tools.readthedocs.io/en/main/", ""),
    # "nwbconversiontool-src": ("https://github.com/catalystneuro/nwb-conversion-tools/", ""),
    # "nwbinspector-docs": ("https://nwbinspector.readthedocs.io/en/add_docs/", ""),
    # "ndx-template-docs": ("https://github.com/nwb-extensions/ndx-template", ""),
    # "ndx-template-src": ("https://github.com/nwb-extensions/ndx-template", ""),
    # "ndx-catalog": ("https://nwb-extensions.github.io/", ""),
    # "ndx-catalog-github-org": ("https://github.com/nwb-extensions/", ""),
    # "hdmf-docutils-docs": ("https://github.com/hdmf-dev/hdmf-docutils", ""),
    # "hdmf-docutils-src": ("https://github.com/hdmf-dev/hdmf-docutils", ""),
    # "nwb-schema-language-docs": ("https://schema-language.readthedocs.io/en/latest/", ""),
    # "nwb-schema-docs": ("https://nwb-schema.readthedocs.io/en/latest/", ""),
    # "nwb-schema-src": ("https://github.com/NeurodataWithoutBorders/nwb-schema", ""),
    # "hdmf-common-schema-docs": ("https://hdmf-common-schema.readthedocs.io/en/stable/", ""),
    # "hdmf-common-schema-src": ("https://github.com/hdmf-dev/hdmf-common-schema", ""),
    # "nwb-github-org": ("http://github.com/NeurodataWithoutBorders", ""),
    # "hdmf-github-org": ("https://github.com/hdmf-dev", ""),
    # "nwb-widgets-docs": ("https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets", ""),
    # "nwb-widgets-src": ("https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets", ""),
    # "caiman-docs": ("https://caiman.readthedocs.io/en/master/", ""),
    "nwb-overview": ("https://nwb-overview.readthedocs.io/en/latest/", ""),
    # "nwb-overview-src": ("https://github.com/NeurodataWithoutBorders/nwb-overview", ""),
    # "nwb-main": ("https://www.nwb.org/", ""),
    "conda-install": (
        "https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html#regular-installation",
        "",
    ),
    "nwbinspector-issues": ("https://github.com/NeurodataWithoutBorders/nwbinspector/issues", ""),
    "nwbinspector-contributing": (
        "https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CONTRIBUTING.md",
        "",
    ),
    "dandi-archive": ("https://dandiarchive.org", ""),
    "ros3-tutorial": ("https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html", ""),
}

# Use this for mapping for links to commonly used documentation
intersphinx_mapping = {
    # "python": ("https://docs.python.org/3/", None),
    # "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    # "numpy": ("https://numpy.org/doc/stable/", None),
    # "matplotlib": ("https://matplotlib.org", None),
    # "h5py": ("https://docs.h5py.org/en/latest/", None),
    # "hdmf": ("https://hdmf.readthedocs.io/en/latest/", None),
    "pynwb": ("https://pynwb.readthedocs.io/en/stable/", None),
    "nwb-schema": ("https://nwb-schema.readthedocs.io/en/latest/", None),
    # "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    # "nct": ("https://nwb-conversion-tools.readthedocs.io/", None),
}
