name: read_nwbfile Streaming tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  build-and-test:
    name: Streaming tests using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
     run:
       shell: bash -l {0}  # necessary for conda
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]  # TODO: update mac and streaming methods
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags

      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov

      - name: Install package
        run: pip install ".[dandi]"

      - name: Uninstall h5py
        run: pip uninstall -y h5py
      - name: Install ROS3
        run: conda install -c conda-forge h5py

      - name: Run pytest on streaming-based read_nwbfile tests
        run: pytest -rsx --cov=nwbinspector --cov-report xml:./coverage.xml tests/read_nwbfile_streaming_tests.py

      - if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./coverage.xml
